name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - kjanat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 💩
        
        Before you submit, please make sure you've searched existing issues to avoid duplicates.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See Error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can drag and drop images here

  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      multiple: true
      options:
        - Frontend (React)
        - Backend (Node.js/Express)
        - AI Service (Python/FastAPI)
        - Database (PostgreSQL)
        - File Storage (MinIO/S3)
        - Docker Setup
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if frontend issue)
      description: What browser are you using?
      placeholder: ex. Chrome 119, Firefox 118, Safari 17

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: ex. Windows 11, macOS 14, Ubuntu 22.04

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: Console logs, error messages, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
