# Development Docker Compose Override
# This file is used by the DevContainer to avoid port conflicts
# and provide development-specific configurations

services:
  postgres:
    ports:
      - "15432:5432" # Different port to avoid host conflicts
    environment:
      POSTGRES_DB: poo_tracker
      POSTGRES_USER: poo_user
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - poo-postgres_data_dev:/var/lib/postgresql/data
      - ../backend/prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  redis:
    ports:
      - "16379:6379" # Different port to avoid host conflicts
    volumes:
      - poo-redis_data_dev:/data

  minio:
    ports:
      - "19000:9000" # Different port to avoid host conflicts
      - "19002:9002" # Different port to avoid host conflicts
    volumes:
      - poo-minio_data_dev:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: poo-photos

  ai-service:
    ports:
      - "18001:8000" # Different port to avoid host conflicts
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  poo-postgres_data_dev:
  poo-minio_data_dev:
  poo-redis_data_dev:
